---
- hosts: machine2
  force_handlers: true
  tasks:
    - name: task1
      shell: echo hello > /home/ansible/somehandler.txt
      notify: handler1
    - name: task2
      command: something
  handlers:
    - name: handler1
      file: path=/home/ansible/handler.txt state=touch

