---
- hosts: machine2
  become: yes
  vars:
    - var1: variable4
    - var2: variable2
  vars_prompt:
    - name: var3
      prompt: Enter the user name you want to create >
  tasks:
    - name: task1
      shell: echo '{{ var1 }}' > /home/ansible/variable.txt
    - name: file
      file: path='/home/ansible/{{ var2 }}.txt' state=touch
    - name: create user
      user: name='{{ var3 }}' state=present  
